image: snapcore/snapcraft:stable

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt update && apt upgrade -y
          - apt install -y python3-pip
          - /snap/bin/snapcraft
