image: snapcore/snapcraft:stable

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt update && apt dist-upgrade -y
          - SNAPCRAFT_CONTAINER_BUILDS=1 /snap/bin/snapcraft
