image: snapcore/snapcraft:stable

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt update && apt dist-upgrade -y
          - pwd
          - ls
          - /snap/bin/snapcraft
