---
name: reporter
version: '1'
version-script: 'date +%y.%j'
summary: Reporting API
description: |
 Receiver endpoint for Reporting API

grade: devel
confinement: strict
base: core18

apps:
  reporter:
    plugs:
    - network-bind  # for accepting HTTP connections
    - network       # for connecting to PostgreSQL
    command: server

parts:

  reporter:
    source: git@bitbucket.org:kravietz/reporter.git
    plugin: python
    python-version: python3
    requirements: requirements.txt
    override-build: |
      pip3 install safety bandit pytest
      python3 -m pytest reporter/test.py
      python3 -m safety check
      python3 -m bandit reporter/server.py
      pip3 uninstall -y safety bandit pytest
      snapcraftctl build
      cp -a reporter $SNAPCRAFT_PART_INSTALL/reporter
      cd $SNAPCRAFT_PART_INSTALL/reporter
      python3 -OO -m compileall .

  wrappers:
    plugin: dump
    source: wrappers/
