---
name: reporter
version: '1'
version-script: 'date +%y.%j'
summary: Reporting API
description: |
 Receiver endpoint for Reporting API

grade: devel
confinement: strict

apps:
  reporter:
    plugs:
    - network-bind  # for accepting HTTP connections
    - network       # for connecting to PostgreSQL
    command: server

parts:

  reporter:
    source: git@bitbucket.org:kravietz/reporter.git
    plugin: python
    python-version: python3
    requirements: requirements.txt
    override-pull: |
      env
      ls
    override-build: |
      snapcraftctl build
      cp -a reporter $SNAPCRAFT_PART_INSTALL/reporter
      cd $SNAPCRAFT_PART_INSTALL/reporter
      python3 -OO -m compileall .

  wrappers:
    plugin: dump
    source: wrappers/
